select * from student;
select * from university;
select * from faculty;
select * from specialization;
select * from default_schema.group; select * from address;
select * from city;
select * from country;
select * from postal_code; select * from street;
select * from phone_number; select * from passport_data; select * from region;
select * from district;
select * from first_name; select * from last_name;