insert into address (id, country_id, distirct_id, region_id, city_id, street_id, house_number, flat_number, phone_number, email, skype, telegram, house_pavilion, postal_code_id) values
(1, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Независимости' and type = 'проспект'), 42, 24,
(select id from phone_number where value = 1111111 and operator_code = 33), 'vasya@gmail.com', 'vasya_skype', '@vasya', 'A', (select id from postal_code where value = 223040)),
(2, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Независимости' and type = 'проспект'), 44, 66,
(select id from phone_number where value = 2222222 and operator_code = 29), 'petya@gmail.com', 'petya_skype', '@petya', null, (select id from postal_code where value = 223040)),
(3, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Победителей' and type = 'проспект'), 44, 56,
(select id from phone_number where value = 3333333 and operator_code = 29), 'masha@gmail.com', 'masha_skype', '@masha', null, (select id from postal_code where value = 223040)),
(4, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Победителей' and type = 'проспект'), 77, 65,
(select id from phone_number where value = 4444444 and operator_code = 44), 'katya@gmail.com', 'katya_skype', '@katya', null, (select id from postal_code where value = 223040)),
(5, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Московская' and type = 'улица'), 66, 13,
(select id from phone_number where value = 5555555 and operator_code = 33), 'kostya@gmail.com', 'kostya_skype', '@kostya', 'Б', (select id from postal_code where value = 223040)),
(6, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Минск'), (select id from street where name='Московская' and type = 'улица'), 133, 55,
(select id from phone_number where value = 6666666 and operator_code = 33), 'nadya@gmail.com', 'nadya_skype', '@nadya', null, (select id from postal_code where value = 223040)),
(7, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Гомельская'),
(select id from region where name = 'Гомельский'), (select id from city where name = 'Гомель'),
(select id from street where name='Кривошеина' and type = 'улица'), 55, 44,
(select id from phone_number where value = 7777777 and operator_code = 44), 'egor@gmail.com', 'egor_skype', '@egor', null, (select id from postal_code where value = 223040)),
(8, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Лесной'), (select id from street where name='К.Маркса' and type = 'улица'), 123, 32,
(select id from phone_number where value = 8888888 and operator_code = 33), 'misha@gmail.com', 'misha_skype', '@misha', null, (select id from postal_code where value = 223040)),
(9, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Минская'),
(select id from region where name = 'Минский'), (select id from city where name = 'Лесной'), (select id from street where name='Александрова' and type = 'улица'), 15, 66,
(select id from phone_number where value = 9999999 and operator_code = 770), 'ulad@gmail.com', 'ulad_skype', '@ulad', 'A', (select id from postal_code where value = 223040)),
(10, (select id from country where name = 'Республика Беларусь'), (select id from district where name = 'Брестская'),
(select id from region where name = 'Брестский'), (select id from city where name = 'Кобрин'),
(select id from street where name='Дружная' and type = 'улица'), 12, 55,
(select id from phone_number where value = 1010101 and operator_code = 774), 'nikita@gmail.com', 'nikita_skype', '@nikita', null, (select id from postal_code where value = 223040));