insert into student (id, first_name_id, last_name_id, patronymic_id, enter_date, finish_date, passport_data_id,
birthday, updated_at, faculty_id, specialization_id, group_id, university_id, course, address_id) values
(1, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Бадюля'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='AB43434FQ'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name = 'ИиТП'),
(select id from db.group where group_number='753501'), (select id from university where short_name='БГУИР'), 3,
1),
(2, (select id from first_name where value = 'Петр'), (select id from last_name where value = 'Артемюк'),
(select id from patronymic where value = 'Владимирович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='FF55434FDAC'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753501'), (select id from university where short_name='БГУИР'), 3,
2),
(3, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Астапенко'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='AA66GGN76'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753501'), (select id from university where short_name='БГУИР'), 3,
3),
(4, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Азанович'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='77YUHA543'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753501'), (select id from university where short_name='БГУИР'), 3,
4),
(5, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Красовский'),
 (select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='655GGHB'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753502'), (select id from university where short_name='БГУИР'), 3,
5),
(6, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Кугуков'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='4342FFFBN'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753503'), (select id from university where short_name='БГУИР'), 3,
6),
(7, (select id from first_name where value = 'Екатерина'), (select id from last_name where value = 'Котусева'),
(select id from patronymic where value = 'Александровна'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='667HHGn8I'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753502'), (select id from university where short_name='БГУИР'), 3,
7),
(8, (select id from first_name where value = 'Василий'), (select id from last_name where value = 'Кравченко'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='FGgYYu55'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753503'), (select id from university where short_name='БГУИР'), 3,
8),
(9, (select id from first_name where value = 'Андрей'), (select id from last_name where value = 'Бадюля'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='GGYHnN'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),

(select id from db.group where group_number='753502'), (select id from university where short_name='БГУИР'), 3,
9),
(10, (select id from first_name where value = 'Виктор'), (select id from last_name where value = 'Бадюля'),
(select id from patronymic where value = 'Александрович'), '2017-06-01', '2021-06-01', (select id from passport_data where unique_id='ACBC5454'), '2000-01-01', current_timestamp(),
(select id from faculty where short_name='ФКСиС'), (select id from specialization where short_name='ИиТП'),
(select id from db.group where group_number='753502'), (select id from university where short_name='БГУИР'), 3,
10);